### ISSUE TITLE
Importing the Package in Python3.10

### ISSUE THREAD

**Issue by SvenDierfeld** [jsford64/jiffy-compression#3]
Hallo jsford64,

I am excited to try your repository. We need to send PointClouds over 5G to our EdgeCloud and the Pointcloud really is our biggest component at the moment.

After successful installation using pip I try to import this package:
```
$ python3.10
Python 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jiffy-lidar as jf
  File "<stdin>", line 1
    import jiffy-lidar as jf
                ^
SyntaxError: invalid syntax
```

So the dash seems to be a problem, so I work around it using importlib but this doesn't seem to work as intended:
```
>>> import importlib
>>> jf = importlib.import_module("jiffy-lidar")
>>> jf.StreamWriter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'jiffy-lidar' has no attribute 'StreamWriter'
```
In your example I see you doing it by including the path, which I would like to avoid as I installed it using pip:
```
import os
import sys
import path
sys.path.append(path.Path(__file__).abspath().parent.parent)
import jiffy-lidar as jf
```

What is the intended way to import this package?

I look forward to hearing from you and thank you

**Comment by jsford64** [comment]
Changed the PyPi.org name from jiffy-lidar (bad python module name) to jiffyCodec.
Also updated the examples and tests to use the pip installed version.

You should now be able to install with: pip install jiffyCodec

then in your python file:
import jiffyCodec as jf

Sorry- I am new at the python packaging process!

**Comment by jsford64** [comment]
Let me know if you have any further questions or problems, and if you get it working, give me your feedback too!

**Comment by SvenDierfeld** [comment]
No problem, it works as intended now. Thank you very much, also for the quick answer!
