### ISSUE TITLE
ByteStream.read(4) returning empty bytes

### ISSUE THREAD

**Issue by SvenDierfeld** [jsford64/jiffy-compression#4]
Hallo again,

I ran into a problem using your library. So I am generating some random frames and encoded them, but while decoding it seems like the StreamReader can't read from the ByteStream. Here is my code:

```
import sys  
import jiffyCodec as jf
import numpy as np


def compress_multiple_frames(frames:list, precision:int=1):
    '''
    frames: list of frames -> each frame is in spherical 2D coordinates with potentially multiple scans (range, intensity, ...)
    '''

    frames_per_group = len(frames)
    print("Frames per group: {}".format(frames_per_group))

    scans_per_frame = len(frames[0])
    print("Scans per Frame: {}".format(scans_per_frame))

    # Open the jiffy encoding stream.    
    stream = jf.StreamWriter(b'', 
                            scansPerFrame=scans_per_frame, 
                            framesPerGroup=frames_per_group, 
                            precision=precision)

    for frame in frames:
        stream.encode(frame)

    # bytestream = b'your_processed_bytestream'
    bytestream = stream.byteStream

    return bytestream


if __name__ == "__main__":

    precision = 1 # in [mm] (Should be the precision of the LiDAR Sensor)

    # Generate some example frames to test the code
    nr_of_frames = 1
    nr_of_scans = 1
    frames = []
    for i in range(nr_of_frames):

        frame = []
        for r in range(nr_of_scans):
            frame.append(40*np.random.rand(10, 5))

        frames.append(frame)

    # compress data using jiffyCodec
    compressed_bytestream = compress_multiple_frames(frames=frames, precision=precision) 
    
    # Calculate the size of the original data
    original_size_bytes = 0
    for frame in frames:
        for scan in frame:
            original_size_bytes += scan.size * scan.itemsize

    # log to console
    print("Size of frames: {}".format(original_size_bytes))
    print("Size of bytestream: {}".format(len(compressed_bytestream.getBuffer())))
    print("Compression ratio: {:.3f}".format(original_size_bytes/len(compressed_bytestream.getBuffer())))
    print("The bytestream: {}".format(compressed_bytestream.getBuffer()))

    print("MAGIC: {}".format(compressed_bytestream.read(4)))

    stream = jf.StreamReader(byteStream=compressed_bytestream)
    print(list(stream.decode()))
```

And this is the output:
```
Frames per group: 1
Scans per Frame: 1
Size of frames: 400
Size of bytestream: 111
Compression ratio: 3.604
The bytestream: b'JFFY\x03\x00\n\x00\x00\x00\x05\x00\x00\x00\x01\x01\x00\x00\x00\x01\x00\xa6\xff\xff\xff?\x10\x00\x00\x00(\xb5/\xfd \x079\x00\x00\xff\xff\xff\xff\xff\xff\x03d<\x00\x00@2\x00\x00\x00\x00\x00\x00\x00\xba\x8e\xc5\x9a\x8e\x8f\xb4\x91\x94\x9f\x87\x89\x8b\xb2\xb3\x9a\x87\x95\x87\xa0\x8f\x8d\xaa\x82\x98\xb1\x87\x82\x92\x9e\x86\xc5\x9e\x97\xba\x8a\x84\x97\x97\x99\x88\xac\xad\xbe\x91\x8e\x8b\xad\xb2\x95\x00\x00'
MAGIC: b''
Traceback (most recent call last):
  File "/workspace/ros2_ws/src/mqtt_sender/src/jiffy_decode_error.py", line 67, in <module>
    print(list(stream.decode()))
  File "/usr/local/lib/python3.10/dist-packages/jiffyCodec.py", line 1223, in decode
    self.readHeader()
  File "/usr/local/lib/python3.10/dist-packages/jiffyCodec.py", line 1122, in readHeader
    raise ValueError('ByteStream is not a Jiffy compressed file.')
ValueError: ByteStream is not a Jiffy compressed file.
```
`compressed_bytestream.read(4)` returns empty bytes. And that results into the MAGIC number not being found.

Please let me know if there is any error in the code.

**Comment by jsford64** [comment]
Hi Sven,

There are two problems:

1) On this line: 
	frame.append(40*np.random.rand(10, 5))
The scan size is set to [10,5] or 10 lines and 5 columns. The actual minimum size is [1,8] which is undocumented,
but it is also not a reasonable size for a real lidar scan. 

2) The bytestream object is analogous to a file (it can also BE a file if you initialize it that way), and it has a read/write position pointer that it maintains.

So I changed your code:

>     # log to console
>     print("Size of frames: {}".format(original_size_bytes))
>     print("Size of bytestream: {}".format(len(compressed_bytestream.getBuffer())))
>     print("Compression ratio: {:.3f}".format(original_size_bytes/len(compressed_bytestream.getBuffer())))
>     print("The bytestream: {}".format(compressed_bytestream.getBuffer()))
> 
>     print("MAGIC: {}".format(compressed_bytestream.read(4)))
> 
>     stream = jf.StreamReader(byteStream=compressed_bytestream)
>     print(list(stream.decode()))


to this code:

# log to console
    print("Size of frames: {}".format(original_size_bytes))
    print("Size of bytestream: {}".format(len(compressed_bytestream.getBuffer())))
    print("Compression ratio: {:.3f}".format(original_size_bytes/len(compressed_bytestream.getBuffer())))
    print("The bytestream: {}".format(compressed_bytestream.getBuffer()))

    # Rewind the bytestream to the beginning.
    # This is necessary because the bytestream read/write position 
    # is still at the end of the stream waiting for more frames to compress.
    compressed_bytestream.rewind()

    print("MAGIC: {}".format(compressed_bytestream.read(4)))

    # Rewind the bytestream to the beginning.
    # This is necessary because the bytestream read/write position
    # has been advanced from the start of the buffer by 4 bytes 
    # in the previous read operation.
    compressed_bytestream.rewind()

    stream = jf.StreamReader(byteStream=compressed_bytestream)
    print(list(stream.decode()))


Let me know if you have any other issues.

Jeff

**Comment by SvenDierfeld** [comment]
Hello Jeff,

thank you for your help. Now it works.

Greetings
