### ISSUE TITLE
Compressing LiDAR points recorded in ROS bags

### ISSUE THREAD

**Issue by ylee079** [jsford64/jiffy-compression#5]
Hi, great work and great paper. I am trying to compress the LiDAR points recorded in huge ROS bags. Can I know how do I do that with this library?

**Comment by jsford64** [comment]
Hi ylee079,

We are working to improve compression, port the code to C++ and add the ability to interface with ROS. We would like to understand your environment a little more- what sensor, configuration, data types, use case, workflow, etc. Knowing that information will help guide our development.

Are you interested in having a conference call to discuss this further?

Jeff
